version: '3.4'
services:
    web:
        build: .
        command: 'bin/run-dev.sh'
        tty: true
        env_file:
            - .env
        depends_on:
            - postgres
        volumes:
            - ./:/app
        ports:
            - '8000:8000'

    postgres:
        image: 'postgres:12.2-alpine'
        environment:
            POSTGRES_USER: camping
            POSTGRES_PASSWORD: password

    node:
        image: 'node:14.0.0-stretch'
        working_dir: /app
        tty: true
        volumes:
            - ./:/app
        ports:
            - '39785:39785'
